name: ML CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt', 'requirements-dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Lint (black)
        run: black --check .

      - name: Lint (flake8)
        run: flake8 .

      - name: Run tests
        run: |
          export PYTHONPATH=$PWD
          pytest -q

      - name: Generate synthetic dataset for CI
        run: |
          python scripts/synthetic_wdbc.py -o data/ci_sample.csv -n 120 --seed 42

      - name: Fast training (CI)
        run: |
          python scripts/train_fast_ci.py -i data/ci_sample.csv -o outputs_ci --cv 3

      - name: Upload CI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-outputs
          path: |
            outputs_ci/**
            data/ci_sample.csv
